config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "callbacks" }

  resources :gardens do
  	resources :plants, only: [:new, :create]
    resources :garden_plants, except: [:edit, :update]
  end

  resources :plants, only: [:show, :index]

  namespace :admin do
    resources :plants
  end


  # resources :garden_plants, only: [:destroy], as: 'delete_garden_plant'
  
  get 'gardens/:garden_id/garden_plants/:garden_plant_id/water_plant', to: 'garden_plants#water_plant', as: 'water_plant'
  get 'gardens/:garden_id/plants/:id/add_garden_plant', to: 'garden_plants#add_garden_plant', as: 'add_garden_plant'
		# clean this up
end

app/models/plant.rb
class Plant < ApplicationRecord
	validates_presence_of :name, :water_frequency
	validates_uniqueness_of :name
	has_many :garden_plants
	has_many :gardens, through: :garden_plants
	
	# add scope method for plants that need watering most frequently
	# scope :high_demand, -> {where("water_frequency < ?", 15).max}
	scope :low_demand, -> {where("water_frequency > ?", 15).max}
end

app/controllers/admin/plants_controller.rb
class Admin::PlantsController < ApplicationController
	before_action :is_admin, :set_plant#, except: [:index]

	def edit
	end

	def update
		@plant.update(plant_params)

		redirect_to plant_path(@plant)
	end

	def destroy
		@plant.garden_plants.destroy_all
		@plant.destroy
		
		redirect_to root_path
	end

	private

	def set_plant
		@plant = Plant.find(params[:id])
	end

	def is_admin
		unless current_user.admin
			redirect_to root_path
		end
	end

	def plant_params
		params.require(:plant).permit(:name, :genus, :water_frequency)
	end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
	before_action :set_plant, except: [:new, :create, :index]

	def index
		@plants = Plant.all
	end

	def new
		# if params[:garden_id]
		# 	@garden = Garden.find(params[:garden_id])
		# end
		@plant = Plant.new
	end

	def create
		@plant = Plant.create(plant_params)

		if @plant.valid?
			if params[:garden_id]
				@garden = Garden.find(params[:garden_id])
				@garden.plants << @plant
			
				redirect_to garden_path(@garden)
			else
				@plant.save

				redirect_to @plant
			end		
		else
			@errors = @plant.errors

			render :new
		end
	end

	def show
		# if params[:garden_id]
		# 	@garden_plant = GardenPlant.find(params[:id])
		# 	@plant = @garden_plant.plant
		# else
		@plant = Plant.find(params[:id])
		# end

	end

	private

	def set_plant
		if !params[:garden_id]
			@plant = Plant.find(params[:id])
		end
	end

	def plant_params
		params.require(:plant).permit(:name, :genus, :water_frequency, :id)
	end

end

app/helpers/plants_helper.rb
module PlantsHelper

  def overdue_notice(garden_plant)
    if (Time.now - garden_plant.last_watered) > (garden_plant.plant.water_frequency * 86400)
      content_tag(:div, "Plant is Overdue for Watering!")
    end
  end

end

app/views/plants/_form.html.erb
<%= form_for :plant, :url => {:controller => 'plants', :action => 'create'} do |f| %> <br>

<%= f.label 'Common Name:' %>
<p><%= f.text_field :name %></p>

<%= f.label :genus %>
<p><%= f.text_field :genus %></p>

<%= f.label 'Water Frequency' %>
<p><%= f.number_field :water_frequency, :min => 1 %></p>

<p><%= f.submit %></p>
<% end %>

app/views/plants/_plant.html.erb
<h2><strong>Common Name: </strong><%= plant.name %></h2>

<p>Genus: <%= plant.genus %></p>
<p>Watering Frequency: Every <%= plant.water_frequency %> Days</p>

app/views/plants/edit.html.erb
Edit Plant:

<%#= render partial: 'form', locals: {:plant => @plant} %>
<%= form_for @plant, :url => {:controller => 'plants', :action => 'update'} do |f| %> <br>

<%= f.label 'Common Name:' %>
<p><%= f.text_field :name %></p>

<%= f.label :genus %>
<p><%= f.text_field :genus %></p>

<%= f.label 'Water Frequency' %>
<p><%= f.number_field :water_frequency %></p>

<p><%= f.submit %></p>
<% end %>

app/views/plants/index.html.erb
<h1>All Plants</h1>

<h2>Lowest Demand Plant: <%= Plant.low_demand.name %></h2>

<br>
<% @plants.each do |plant| %>
<p><%= link_to plant.name, plant_path(plant) %> <%if current_user.admin %><%= link_to "Edit", edit_admin_plant_path(plant) %><%end%></p>
<% end %>

app/views/plants/new.html.erb
<% if @errors %><% @errors.messages.each do |e| %>
<%= content_tag(:li, e.join(" ").gsub("_", " ").capitalize) %>
<% end %><% end %>

<h3>Make a New Plant:</h3> 

<%= render partial: 'form', locals: {:plant => @plant} %>

app/views/plants/show.html.erb
<%= render partial: 'plant', :locals => {:plant => @plant} %>