config/routes.rb
Rails.application.routes.draw do
  root 'welcome#home'

  devise_for :users, :controllers => { :registrations => "registrations", :omniauth_callbacks => "callbacks" }

  resources :gardens do
  	resources :plants, only: [:new, :create]
    resources :garden_plants, except: [:edit, :update]
  end

  resources :plants, only: [:show, :index]

  namespace :admin do
    resources :plants
  end


  # resources :garden_plants, only: [:destroy], as: 'delete_garden_plant'
  
  get 'gardens/:garden_id/garden_plants/:garden_plant_id/water_plant', to: 'garden_plants#water_plant', as: 'water_plant'
  get 'gardens/:garden_id/plants/:id/add_garden_plant', to: 'garden_plants#add_garden_plant', as: 'add_garden_plant'
		# clean this up
end

app/models/garden.rb
class Garden < ApplicationRecord
	belongs_to :user
	has_many :garden_plants
	has_many :plants, through: :garden_plants
	validates_presence_of :name
	# accepts_nested_attributes_for :plants

end

app/controllers/gardens_controller.rb
	class GardensController < ApplicationController
	before_action :set_garden, only: [:show, :edit, :update, :destroy]
	before_action :is_owner, except: [:new, :create, :index]

	def new
		@garden = Garden.new
	end

	def create
		@garden = Garden.new(garden_params)
		@garden.user = current_user

		if @garden.save

			redirect_to garden_path(@garden)
		else

			render :new
		end
	end

	def edit
	end

	def update
		@garden.update(garden_params)

		redirect_to @garden
	end

	def show
	end

	def destroy
		@garden.garden_plants.destroy_all
		@garden.destroy

		redirect_to root_path
	end

	def index
		@gardens = current_user.gardens

		# flash[:notice] = "There "
		# 	redirect_to 
			# @gardens = Garden.all
		# end
	end

	private

	def set_garden
		@garden = Garden.find(params[:id])
	end

	def is_owner
		unless @garden.user == current_user
			flash[:notice] = "You Do Not Have Permissions to View/Update This Garden"
			redirect_to root_path
		end
	end

	def garden_params
		params.require(:garden).permit(:name)
	end

end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/views/gardens/_form.html.erb
<%= form_for :garden do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.submit %></p>
<% end %>

app/views/gardens/edit.html.erb
Edit This Garden:

<%#= render partial: 'form', locals: {:garden => @garden} %> 
<%= form_for @garden, :url => {:controller => 'gardens', :action => 'update'} do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.submit %></p>
<% end %>	

app/views/gardens/index.html.erb
<h3><%= link_to "Make New Garden", new_garden_path %></h3>
<%unless current_user.gardens%>
<h2>All <%if current_user.username != "" %><%= current_user.username + "'s " %><% end %>Gardens: </h2>
<%end%>

<ul>
<% @gardens.each do |garden| %>
<li><%= link_to garden.name, garden_path(garden) %> - <%= garden.garden_plants.count %> Plants </li>
<% end %>
</ul>

app/views/gardens/new.html.erb
Make a New Garden:

<%#= render partial: 'form', locals: {:garden => @garden} %> 
<%= form_for @garden, :url => {:controller => 'gardens', :action => 'create'} do |f| %>
<p><%= f.label :name %></p>
<p><%= f.text_field :name %></p>
<p><%= f.submit %></p>
<% end %>

app/views/gardens/show.html.erb
<h3>Garden Name: <%= @garden.name %> - <%= link_to "Edit Garden", edit_garden_path(@garden) %>
 	<%= link_to "Delete Garden", garden_path(@garden), method: :delete, data: { confirm: 'Are you sure?' } %>
</h3> 

<ul><% @garden.garden_plants.reverse.each do |gp| %>
<li><%= link_to gp.plant.name, plant_path(gp.plant) %>, Last Watered: <%= normalize_time(gp.last_watered) %>
	- <%= link_to "View Plant", garden_garden_plant_path(@garden, gp) %>
	<% if overdue_notice(gp) %> - <%= link_to "Water Plant", water_plant_path(@garden, gp) %> - <% end %>
 	- <%= link_to "Mulch Plant", garden_garden_plant_path(@garden, gp),
			method: :delete, data: { confirm: 'Are you sure?' } %>

<p><%= overdue_notice(gp) %></p></li><% end %></ul>

<h3>Select a Plant to Add to Your Garden:</h3>

<%= form_tag add_garden_plant_path(@garden), :method => :get do %>
<%= collection_select :plant, :id, Plant.order('name ASC'), :id, :name %>
<%= submit_tag "Add Plant" %>
<% end %>

<h3>OR</h3>

<%= link_to "Make a New Plant", new_garden_plant_path(@garden) %>
<br><br>